---
title: "AR(2) modeling"
author: "An Tran"
date: "9/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  
```{r}
library(astsa)
require(lattice)
library(xts)
library(readxl)
library(VIM)
library(naniar)
library(ggplot2)
```

```{r}
#importing the data
us_ir <- read_excel("Data/Data_interest rate_all terms.xlsx")
```

```{r}
#adjusting column names
colnames(us_ir) <- c("DATE", "mth1", "mth3", "mth12", "mth36", "mth60")
mth1 <- ts(us_ir$mth1, start=c(1970, 1), end=c(2020, 01))
mth3 <- ts(us_ir$mth3, start=c(1970, 1), end=c(2020, 01))
mth12 <- ts(us_ir$mth12, start=c(1970, 1), end=c(2020, 01))
mth36 <- ts(us_ir$mth36, start=c(1970, 1), end=c(2020, 01))
mth60 <- ts(us_ir$mth60, start=c(1970, 1), end=c(2020, 01))
tb = cbind(mth1,mth3,mth12,mth36,mth60)
View(us_ir$mth1)
```

```{r}
#Understanding data
quantile(us_ir$mth3)
quantile(us_ir$mth12, na.rm = TRUE)
quantile(us_ir$mth60)
```

```{r}
#computing the standard deviation
sd(mth3)
sd(mth12, na.rm =  TRUE)
sd(mth60)
```

```{r}
#plotting the missing data in 12-month 
aggr_plot <- aggr(us_ir, 
                  col = c('navyblue','red'), 
                  numbers = TRUE, sortVars = TRUE,                  
                  labels = names(us_ir), 
                  cex.axis=.7, 
                  gap=3, 
                  ylab=c ("Histogram of missing in US variables","Pattern"))

vis_miss(us_ir)
```

#Before Adjustment
```{r}
#Plotting the yield curve full variables
plot.ts(tb,            
         col = c("red","yellow","black","blue","grey"),
         ylim = c(0,20), 
         main = "")
title(main = "The US interest rates with all maturities")

xyplot.ts(tb,superpose=TRUE,auto.key=list(columns=4),xlab = NULL,ylab=" All Yield (%)")

xyplot.ts(cbind(mth3,mth12,mth60),superpose=TRUE,auto.key=list(columns=4),xlab= NULL,ylab=" Observe Yied(%)")
```

```{r}
#Computing the ACF 
acf(na.omit(mth3), lag.max = 4, plot = FALSE)
acf(na.omit(mth3), 
    main = "Sample Autocorrelation for interest rate 3mth before adjustment")

acf(na.omit(mth12), lag.max = 4, plot = FALSE)
acf(na.omit(mth3), 
    main = "Sample Autocorrelation for interest rate 12mth before adjustment")

acf(na.omit(mth60), lag.max = 4, plot = FALSE)
acf(na.omit(mth60), 
    main = "Sample Autocorrelation for interest rate 60mth before adjustment")
```


#After Adjustment
1. log differencing 
formula: Δlog(Yt)=log(Yt)−log(Yt−1)=log(Y/lag(Y))
C=1200 for monthly, C=400 for quarterly (cite: "how..")
stats::lag(1:5, 1)
dplyr::lag(1:5, 1)
Log differencing and its plot

```{r}
#(1st Lag)
quants <- function(series) 
{s <- series
return(
  data.frame("Level" = s, 
             "Logarithm" = log(s), 
             "AnnualGrowthRate" = 1200 * log(s/lag(s)), 
             "1stLagAnnualGrowthRate" = lag(1200 * log(s/lag(s))))) 
} 

mth3_change <- ts(1200 * (log(mth3)/stats::lag(mth3,1)))
mth12_change <- ts(1200 * (log(mth12)/stats::lag(mth12,1)))
mth60_change <- ts(1200 * (log(mth60)/stats::lag(mth60,1)))

par(mfrow = c(1, 2))             ## divide plotting area into 1x2 matrix

acf(na.omit(mth3_change), lag.max = 4, plot = FALSE)
acf(na.omit(mth3_change), 
    main = "Sample Autocorrelation for interest rate 3mth change")

acf(na.omit(mth12_change), lag.max = 4, plot = FALSE)
acf(na.omit(mth12_change), 
    main = "Sample Autocorrelation for interest rate 12mth change")


acf(na.omit(mth60_change), lag.max = 4, plot = FALSE)
acf(na.omit(mth60_change), 
    main = "Sample Autocorrelation for interest rate 36mth change")
```

2. Differcing 
```{r}
diff3_1 = diff(mth3)
diff3_2 = diff(diff3_1)

plot.ts(cbind(mth3,diff3_1,diff3_2))

acf(na.omit(diff3_2), lag.max = 25, plot = FALSE)
acf(na.omit(diff3_2), 
    main = "Sample Autocorrelation for interest rate 3mth change")
```

#AR modelling for 3-month
```{r}
#subset data
Sub3 <- diff3_2 ["1971::2019"]
View(diff3_2)
```

```{r}
#Estimate the model
ar.ols(Sub3,
       order.max = 1,
       demean = FALSE,
       intercept = TRUE)
```

```{r}
#length of data set
N <- length(Sub3)
Sub3_level <- as.numeric(Sub3[-1])
Sub3_lags <- as.numeric(Sub3[-N])
```

```{r}
#estimate the model
armod3 <- lm(Sub3_level ~ Sub3_lags)
```

```{r}
#Robust summary 
coefficients(armod3, vcov. = vcovHC, type="HC1")
```

```{r}
#Non robust 
summary(armod3)$coefficients
```

```{r}
#assign US interest rate change in 2019:12:01
new3 <- data.frame("Sub3_lags" = Sub3_level[N-1])
```

```{r}
#forecast US interest rate change in 2020:01:01
forecast(armod3, newdata = new3 )
```

```{r}
#compute the forecast error
forecast(armod3, newdata = new3)$mean - mth3_change["2019"][1]
```

```{r}
#R^2
summary(armod3)$r.squared
```

```{r}
#SER
summary(armod3)$sigma
```

```{r}
#AR(p) model with dynlm: dynamic linear models and time series regression
mth3_AR2 <- dynlm(ts(Sub3_level) ~ L(ts(Sub3_level))
                  + L(ts(Sub3_level), 2))
coefficients(mth3_AR2, vcov. = sandwich)
summary(mth3_AR2)$r.squared
summary(mth3_AR2)$sigma
```

```{r}
coeftest(mth3_AR2, vcov. = , sandwich)
```

```{r}
# AR(2) forecast of interest rate change in 2020-01-01
forecast <- c("20120-01-01" = coef(mth3_AR2) %*% c(1, Sub3_level[N-1], Sub3_level[N-2]))
```

```{r}
#compute AR(2) forecast error
mth3["2020"][1]-forecast
View(mth3["2020"][1]-forecast)
```

#AR modelling for 12-month
```{r}
diff12_1 = diff(mth12,na.rm =  TRUE)
diff12_2 = diff(diff12_1, na.rm =  TRUE)

plot(cbind(mth12, c(diff12_1), c(diff12_2), type ="1"))

par(mfrow = c(1, 2)) 

acf(na.omit(diff12_2),
    lag.max = 25,
    plot = FALSE,
    na.action = na.pass)

acf(na.omit(diff12_2), 
    main = "Sample Autocorrelation for interest rate 12 mth change",
      na.action = na.pass)
```

```{r}
#subset data
Sub12 <- diff12_2 ["1971::2019"]
View(diff12_2)
```

```{r}
#Estimate the model
ar.ols(Sub12,
       order.max = 1,
       demean = FALSE,
       intercept = TRUE,
       na.action = na.fail)
```

```{r}
#length of data set
N <- length(Sub12)
Sub12_level <- as.numeric(Sub12[-1])
Sub12_lags <- as.numeric(Sub12[-N])
```

```{r}
#estimate the model
armod12 <- lm(Sub12_level ~ Sub12_lags)
```

```{r}
#Robust summary 
coefficients(armod12, vcov. = vcovHC, type="HC1")
```

```{r}
#Non robust 
summary(armod12)$coefficients
```

```{r}
#assign US interest rate change in 2019:12:01
new12 <- data.frame("Sub12_lags" = Sub12_level[N-1])
```

```{r}
#forecast US interest rate change in 2020:01:01
forecast(armod12, newdata = new12 )
```

```{r}
#compute the forecast error
forecast(armod12, newdata = new12)$mean - mth12_change["2019"][1]
```

```{r}
#R^2
summary(armod12)$r.squared
```

```{r}
#SER
summary(armod12)$sigma
```

```{r}
#AR(p) model with dynlm: dynamic linear models and time series regression
mth12_AR2 <- dynlm(ts(Sub12_level) ~ L(ts(Sub12_level))
                  + L(ts(Sub12_level), 2))
coefficients(mth12_AR2, vcov. = sandwich)
summary(mth12_AR2)$r.squared
summary(mth12_AR2)$sigma
```

```{r}
coeftest(mth12_AR2, vcov. = , sandwich)
```

```{r}
# AR(2) forecast of interest rate change in 2020-01-01
forecast <- c("20120-01-01" = coef(mth12_AR2) %*% c(1, Sub12_level[N-1], Sub12_level[N-2]))
```

```{r}
#compute AR(2) forecast error
mth12["2020"][1]-forecast
View(mth12["2020"][1]-forecast)
```
#AR modelling for 60-month   

```{r}
diff60_1 = diff(mth60)
diff60_2 = diff(diff60_1)

plot(cbind(mth60, c(diff60_1), c(diff60_2), type ="1"))

par(mfrow = c(1, 2)) 

acf(na.omit(diff60_2),
    lag.max = 25,
    plot = FALSE)

acf(na.omit(diff60_2), 
    main = "Sample Autocorrelation for interest rate 60 mth change")
```

```{r}
#subset data
Sub60 <- diff60_2 ["1971::2019"]
View(diff60_2)
```

```{r}
#Estimate the model
ar.ols(Sub60,
       order.max = 1,
       demean = FALSE,
       intercept = TRUE)
```

```{r}
#length of data set
N <- length(Sub60)
Sub60_level <- as.numeric(Sub60[-1])
Sub60_lags <- as.numeric(Sub60[-N])
```

```{r}
#estimate the model
armod60 <- lm(Sub60_level ~ Sub60_lags)
```

```{r}
#Robust summary 
coefficients(armod60, vcov. = vcovHC, type="HC1")
```

```{r}
#Non robust 
summary(armod60)$coefficients
```

```{r}
#assign US interest rate change in 2019:12:01
new60 <- data.frame("Sub60_lags" = Sub60_level[N-1])
```

```{r}
#forecast US interest rate change in 2020:01:01
forecast(armod60, newdata = new60 )
```

```{r}
#compute the forecast error
forecast(armod60, newdata = new60)$mean - mth60_change["2019"][1]
```

```{r}
#R^2
summary(armod60)$r.squared
```

```{r}
#SER
summary(armod60)$sigma
```

```{r}
#AR(p) model with dynlm: dynamic linear models and time series regression
mth60_AR2 <- dynlm(ts(Sub60_level) ~ L(ts(Sub60_level))
                  + L(ts(Sub60_level), 2))
coefficients(mth60_AR2, vcov. = sandwich)
summary(mth60_AR2)$r.squared
summary(mth60_AR2)$sigma
```

```{r}
coeftest(mth60_AR2, vcov. = , sandwich)
```

```{r}
# AR(2) forecast of interest rate change in 2020-01-01
forecast <- c("20120-01-01" = coef(mth60_AR2) %*% c(1, Sub60_level[N-1], Sub60_level[N-2]))
```

```{r}
#compute AR(2) forecast error
mth60["2020"][1]-forecast
View(mth60["2020"][1]-forecast)
```
                    
                    